# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ddf749a91399fdfdf79dcff44c2f301fcf6a5cf339813b15f183061317b0f523bd3d3d292c2070cf38e0bf30df467b8bb82861842f183bada484558c869a85

test:
  secret_key_base: 307da00434ea01e75fd3c846aab9618e96a7033682783c0c4ca936e6ab3d257544a6928962076e7dac23de24a68b77d187c83c4518fccba9433ff97519816d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
